version: "3.9"

services:
  api:
    image: nginx-recipes
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - REDIS_URI=redis:6379
    networks:
      - app_network
    external_links:
      - mongodb
      - redis
    scale: 5 

  redis:
    image: redis
    networks:
      - app_network
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app_network
  
  nginx:
    image: nginx
    ports: 
      - 80:80    
    volumes:  
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app_network  

networks:
  app_network:      